#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bundle-OpenInteract2
version:      1.03
version_from: OpenInteract2.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
